# Generated by Django 5.2.5 on 2025-08-11 10:02

import coupons.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CouponBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("fixed", "fixed"), ("percent", "percent")],
                        max_length=10,
                    ),
                ),
                ("amount", models.IntegerField(blank=True, null=True)),
                ("percent", models.IntegerField(blank=True, null=True)),
                ("per_user_limit", models.IntegerField(default=1)),
                ("total_limit", models.IntegerField()),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="IdempotencyKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("user_id", models.CharField(max_length=64)),
                (
                    "request_fingerprint",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("response_status", models.IntegerField(blank=True, null=True)),
                ("response_body", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=coupons.models.idempotency_default_expiry
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=16, unique=True)),
                ("issued_to", models.CharField(blank=True, max_length=64, null=True)),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("issued", "issued"),
                            ("redeemed", "redeemed"),
                            ("cancelled", "cancelled"),
                            ("expired", "expired"),
                        ],
                        default="issued",
                        max_length=12,
                    ),
                ),
                ("redeemed_by", models.CharField(blank=True, max_length=64, null=True)),
                ("redeemed_at", models.DateTimeField(blank=True, null=True)),
                ("order_id", models.CharField(blank=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coupons",
                        to="coupons.couponbatch",
                    ),
                ),
            ],
        ),
    ]
